const A=SCEO;let db,uid,ROOMCODE='',TEAM='',ROOM=null,ACT={},STEP=1,unsubs=[],timerHandle=null,lastAutoKey='';const $=A.$,$$=A.$$;
function setMsg(t,ok=false){$('#joinMsg').className=ok?'okbox':'notice';$('#joinMsg').textContent=t}
function fillTeamSelect(sel,count=5){sel.innerHTML=Array.from({length:count},(_,i)=>`<option value="${i+1}">${i+1}조</option>`).join('')}
function leaveClosedRoom(){unsubs.forEach(fn=>{try{fn()}catch(e){}});unsubs=[];if(timerHandle)clearInterval(timerHandle);ROOMCODE='';TEAM='';ROOM=null;ACT={};STEP=1;lastAutoKey='';localStorage.removeItem('sceo_v2_join');try{const u=new URL(location.href);u.searchParams.delete('room');history.replaceState({},'',u.pathname+(u.search||'')+(u.hash||''));}catch(e){}$('#app').classList.add('hidden');$('#join').classList.remove('hidden');$('#joinRoom').value='';$('#joinTeam').value='1';setTimeout(()=>{$('#joinRoom').value='';$('#joinTeam').value='1'},50);setMsg('수업이 종료되었습니다. 새 수업방 코드를 입력하세요.',true);}
async function init(){if(!A.configReady()){ $('#needSetup').classList.remove('hidden');return}try{const f=await A.firebaseInit();db=f.db;uid=f.uid;$('#join').classList.remove('hidden');fillTeamSelect($('#joinTeam'),12);const saved=JSON.parse(localStorage.getItem('sceo_v2_join')||'null');const qp=new URLSearchParams(location.search).get('room');if(qp&&/^\d{6}$/.test(qp))$('#joinRoom').value=qp;else if(saved)$('#joinRoom').value=saved.room||'';if(saved)$('#joinTeam').value=saved.team||'1'}catch(e){$('#needSetup').classList.remove('hidden');$('#needSetup .warnbox').textContent='연결 실패: '+e.message}}
async function joinRoom(){const room=$('#joinRoom').value.trim(),team=$('#joinTeam').value;if(!/^\d{6}$/.test(room))return setMsg('6자리 방 코드를 입력하세요.');const meta=await A.read(A.roomPath(room,'meta'));if(!meta)return setMsg('수업방을 찾지 못했습니다. 방 코드를 확인하세요.');if(meta.closed)return setMsg('이미 종료된 수업방입니다.');const cfg=await A.read(A.roomPath(room,'config')),t=await A.read(A.roomPath(room,'teams',team));if(!t)return setMsg('이 수업방에는 해당 조가 없습니다.');if(t.deviceUid&&t.deviceUid!==uid)return setMsg(`${team}조는 이미 다른 대표 휴대폰이 연결되어 있습니다. 선생님께 연결 해제를 요청하세요.`);if(!t.deviceUid)await A.set(A.roomPath(room,'teams',team,'deviceUid'),uid);await A.set(A.roomPath(room,'teams',team,'joinedAt'),firebase.database.ServerValue.TIMESTAMP);ROOMCODE=room;TEAM=team;STEP=1;lastAutoKey='';localStorage.setItem('sceo_v2_join',JSON.stringify({room,team}));$('#join').classList.add('hidden');$('#app').classList.remove('hidden');$('#roomLabel').textContent=room;fillTeamSelect($('#teamSelect'),cfg.teamCount);$('#teamSelect').value=team;setStep(1,false);subscribe();}
function setStep(step,rerender=true){STEP=+step;$$('.tab').forEach(b=>b.classList.toggle('on',+b.dataset.step===STEP));if(rerender&&ROOM)render()}
function syncStepFromTeacher(st){let target=null,key='';if(st?.reflectionOpen||st?.phase==='reflection'){target=2;key='reflection'}else if(st?.currentAuction){target=0;key=`auction:${st.currentAuction.id||''}:${st.currentAuction.stage||''}`}else if(st?.offer){target=0;key=`offer:${st.offer.id||''}`}else if(st?.mainSelectionOpen||String(st?.phase||'').startsWith('main-')){target=0;key=`main:${st.phase||''}:${st.mainSelectionMode||''}:${st.mainSelectionOpen?'open':'closed'}`}if(target!==null&&key!==lastAutoKey){lastAutoKey=key;setStep(target,false)}}
function subscribe(){
  unsubs.forEach(fn=>{try{fn()}catch(e){}});unsubs=[];
  ROOM={config:null,state:{},inventory:{},teams:{},mainSelections:{}};
  unsubs.push(A.listen(A.roomPath(ROOMCODE,'meta'),v=>{if(v?.closed)leaveClosedRoom()}));
  const redraw=()=>{const t=ROOM.teams?.[TEAM];if(ROOM.config&&t){$('#budget').textContent=A.money(A.remaining(t,ROOM.config));render()}};
  unsubs.push(A.listen(A.roomPath(ROOMCODE,'config'),v=>{ROOM.config=v||null;redraw()}));
  unsubs.push(A.listen(A.roomPath(ROOMCODE,'state'),v=>{ROOM.state=v||{};syncStepFromTeacher(ROOM.state);redraw()}));
  unsubs.push(A.listen(A.roomPath(ROOMCODE,'inventory'),v=>{ROOM.inventory=v||{};redraw()}));
  unsubs.push(A.listen(A.roomPath(ROOMCODE,'teams',TEAM),v=>{ROOM.teams={[TEAM]:v||null};redraw()}));
  unsubs.push(A.listen(A.roomPath(ROOMCODE,'mainSelections',TEAM),v=>{ROOM.mainSelections={[TEAM]:v||''};redraw()}));
  unsubs.push(A.listen(A.roomPath(ROOMCODE,'activity',TEAM),v=>{ACT=v||{};redraw()}));
}
async function switchTeam(team){if(team===TEAM)return;const t=await A.read(A.roomPath(ROOMCODE,'teams',team));if(t?.deviceUid&&t.deviceUid!==uid){alert(`${team}조는 다른 대표 휴대폰이 연결되어 있습니다.`);$('#teamSelect').value=TEAM;return}if(!t?.deviceUid)await A.set(A.roomPath(ROOMCODE,'teams',team,'deviceUid'),uid);await A.set(A.roomPath(ROOMCODE,'teams',team,'joinedAt'),firebase.database.ServerValue.TIMESTAMP);TEAM=team;localStorage.setItem('sceo_v2_join',JSON.stringify({room:ROOMCODE,team}));subscribe()}
function goto(step){setStep(step,true)}
function saveActivity(patch){ACT={...ACT,...patch};return A.update(A.roomPath(ROOMCODE,'activity',TEAM),patch)}
function bindInputs(){$$('[data-act]').forEach(el=>{const key=el.dataset.act;const handler=()=>saveActivity({[key]:el.type==='checkbox'?el.checked:el.value});el.onchange=handler;if(el.tagName==='TEXTAREA'||el.type==='text'||el.type==='number')el.oninput=handler});$$('[data-arr]').forEach(el=>el.onchange=()=>{const k=el.dataset.arr,a=$$(`[data-arr="${k}"]:checked`).map(x=>x.value);saveActivity({[k]:a})})}
function planHtml(cfg){return `<div class="card"><h2>① 경매 전 · 우리 조 계획</h2><div class="grid"><div class="field"><label>처음 생각한 샌드위치 이름</label><input class="input" data-act="planName" value="${A.esc(ACT.planName||'')}"></div><div class="field"><label>가장 원하는 메인재료</label><select data-act="planMain"><option value="">선택</option>${cfg.mainItems.map(x=>`<option ${ACT.planMain===x.id?'selected':''} value="${x.id}">${A.esc(x.name)}</option>`).join('')}</select></div></div><div class="field"><label>사고 싶은 추가재료</label><div class="choice">${cfg.addonItems.map(x=>`<label class="check"><input type="checkbox" data-arr="planAddons" value="${x.id}" ${(ACT.planAddons||[]).includes(x.id)?'checked':''}>${A.esc(x.name)}</label>`).join('')}</div></div><div class="grid"><div class="field"><label>우리 조 최대 입찰 한도</label><input class="input" type="number" data-act="planMaxBid" value="${A.esc(ACT.planMaxBid||'')}" placeholder="예: 6000"></div><div class="field"><label>왜 이 재료를 원했나요?</label><textarea data-act="planReason">${A.esc(ACT.planReason||'')}</textarea></div></div><div class="okbox">입력 내용은 자동저장됩니다. 계획을 적은 뒤 <b>⚡ 실시간 경매</b> 탭으로 이동하세요.</div></div>`}
function mainSelectionHtml(cfg,t,st){const target=!!st.mainSelectionTargets?.[TEAM],mine=ROOM.mainSelections?.[TEAM]||'';if(!st.mainSelectionOpen)return `<div class="notice">현재 메인 선택은 닫혀 있습니다. 선생님 안내를 기다려 주세요.</div>`;if(!target)return `<div class="okbox">우리 조는 이번 메인 선택 대상이 아닙니다.</div>`;return `<div class="notice"><b>${st.mainSelectionMode==='reselect'?'낙찰 실패 조 재선택':'메인재료 비공개 선택'}</b><br>선택 시간이 열려 있는 동안에는 바꿀 수 있습니다. 다른 조 선택은 보이지 않습니다.</div><div class="items">${cfg.mainItems.map(it=>{const rem=+ROOM.inventory?.[it.id]?.remaining||0;return `<div class="item ${mine===it.id?'contested':''} ${rem<=0?'sold':''}"><b>${A.esc(it.name)}</b><div>${A.money(it.startPrice)} · 남은 ${rem}조분</div><button class="btn chooseMain" data-id="${it.id}" ${rem<=0?'disabled':''}>${mine===it.id?'✓ 선택됨':'선택'}</button></div>`}).join('')}</div>`}
function offerHtml(cfg,o){if(!o)return '';const q=(o.qualifiedTeams||[]).includes(TEAM);if(!q)return `<div class="notice">현재 <b>${A.esc(o.itemName)}</b> 참여 확인 중이지만 우리 조는 이번 품목 참여 조건에 해당하지 않습니다.</div>`;return `<div class="stage">${A.esc(o.itemName)} · 시작가 ${A.money(o.startPrice)}</div><div class="notice">우리 조는 참여할까요? 응답 마감 전에는 바꿀 수 있습니다.</div><div class="controls"><button class="btn offerChoice" data-v="true">참여하기</button><button class="btn secondary offerChoice" data-v="false">이번에는 패스</button></div><div id="myOffer" class="muted"></div>`}
function auctionHtml(cfg,a,t){if(!a)return '';const eligible=(a.eligibleTeams||[]).includes(TEAM);if(a.stage==='prepared')return `<div class="stage">${A.esc(a.itemName)} · ${a.tieRound?'동점 재입찰':'가격경쟁'} 준비</div><div class="notice">${eligible?`우리 조는 대상입니다. 선생님이 시작하면 ${a.duration}초 동안 입찰합니다.`:'우리 조는 이번 가격경쟁 대상이 아닙니다.'}</div>`;let remain=Math.max(0,Math.ceil((a.endsAt-Date.now())/1000));if(!eligible)return `<div class="stage">${A.esc(a.itemName)}</div><div class="timer">${remain}초</div><div class="notice">우리 조는 이번 입찰 대상이 아닙니다. 결과를 기다려 주세요.</div>`;const rem=A.remaining(t,cfg);return `<div class="stage">${A.esc(a.itemName)} · ${a.tieRound?'동점 재입찰':'비공개 입찰'} · 최소 ${A.money(a.minimumBid)}</div><div class="timer">${remain}초</div><div class="field"><label>우리 조 입찰가 · 남은 예산 ${A.money(rem)}</label><input id="bidAmount" class="input" type="number" inputmode="numeric" min="${a.minimumBid}" max="${rem}" placeholder="${a.minimumBid} 이상"></div><button id="bidBtn" class="btn">입찰 확정/수정</button><div id="myBid" class="notice">다른 조 입찰가는 보이지 않습니다.</div>`}
function auctionPage(cfg,t,st){const awards=A.activeAwards(t);let html=`<div class="card"><h2>⚡ 실시간 경매</h2><div class="topbar"><div><b>우리 조 낙찰</b> ${awards.length?awards.map(x=>A.esc(x.itemName)).join(' · '):'아직 없음'}</div><div class="money">${A.money(A.remaining(t,cfg))}</div></div></div>`;html+=`<div class="card"><h2>메인재료</h2>${mainSelectionHtml(cfg,t,st)}</div>`;if(st.offer)html+=`<div class="card"><h2>추가재료/음료 참여</h2>${offerHtml(cfg,st.offer)}</div>`;if(st.currentAuction)html+=`<div class="card"><h2>현재 가격경쟁</h2>${auctionHtml(cfg,st.currentAuction,t)}</div>`;if(st.phase==='reflection'||st.reflectionOpen)html+=`<div class="card"><div class="okbox"><b>경매 종료!</b> 이제 위의 <b>2. 경매 후 비교</b>부터 활동을 이어가세요.</div></div>`;return html}
function actual(t){const a=A.activeAwards(t);return{main:a.find(x=>x.category==='main'),addons:a.filter(x=>x.category==='addon'),drink:a.find(x=>x.category==='drink'),spent:A.spent(t)}}
function step2(cfg,t){const x=actual(t);return `<div class="card"><h2>② 경매 후 · 실제 결과와 비교</h2><div class="grid"><div class="notice"><b>실제 메인</b> ${A.esc(x.main?.itemName||'-')}<br><b>추가재료</b> ${x.addons.length?x.addons.map(a=>A.esc(a.itemName)).join(', '):'-'}<br><b>음료</b> ${A.esc(x.drink?.itemName||'없음')}</div><div class="notice"><b>총 낙찰 지출</b> ${A.money(x.spent)}<br><b>남은 가상예산</b> ${A.money(A.remaining(t,cfg))}</div></div><div class="grid"><div class="field"><label>처음 계획과 달라진 점</label><textarea data-act="changes">${A.esc(ACT.changes||'')}</textarea></div><div class="field"><label>포기한 선택과 이유</label><textarea data-act="forgone">${A.esc(ACT.forgone||'')}</textarea></div></div></div>`}
function step3(cfg){return `<div class="card"><h2>③ 우리 조 샌드위치를 ‘상품’으로 만들기</h2><div class="grid"><div class="field"><label>최종 샌드위치 이름</label><input class="input" data-act="productName" value="${A.esc(ACT.productName||'')}"></div><div class="field"><label>샌드위치 1개 판매가격</label><input class="input" type="number" data-act="salePrice" value="${A.esc(ACT.salePrice||'')}"></div><div class="field"><label>누가 사 먹으면 좋을까요?</label><input class="input" data-act="target" value="${A.esc(ACT.target||'')}"></div><div class="field"><label>한 줄 상품소개</label><input class="input" data-act="tagline" value="${A.esc(ACT.tagline||'')}"></div></div><div class="field"><label>이 가격으로 정한 이유</label><textarea data-act="priceReason">${A.esc(ACT.priceReason||'')}</textarea></div></div>`}
function step4(cfg){return `<div class="card"><h2>④ 조별 경제회의</h2><div class="field"><label>이번 활동에서 경험한 경제개념</label><div class="choice">${cfg.concepts.map(c=>`<label class="check"><input type="checkbox" data-arr="concepts" value="${A.esc(c)}" ${(ACT.concepts||[]).includes(c)?'checked':''}>${A.esc(c)}</label>`).join('')}</div></div><div class="grid3"><div class="field"><label>가장 잘한 경제적 선택</label><textarea data-act="bestChoice">${A.esc(ACT.bestChoice||'')}</textarea></div><div class="field"><label>가장 어려웠던 선택</label><textarea data-act="hardChoice">${A.esc(ACT.hardChoice||'')}</textarea></div><div class="field"><label>다시 한다면 바꿀 전략</label><textarea data-act="retry">${A.esc(ACT.retry||'')}</textarea></div></div></div>`}
function step5(cfg,t){const left=A.remaining(t,cfg);return `<div class="card"><h2>⑤ 남은 예산을 실제 생활이라면?</h2><div class="money">남은 가상예산 ${A.money(left)}</div><div class="notice">예산을 전부 써야 하는 것은 아닙니다. 소비·저축·기부·나눔·예비비 중 어떻게 배분할지 정해 보세요.</div><div class="grid3"><div class="field"><label>추가 소비</label><input class="input" type="number" data-act="leftConsume" value="${A.esc(ACT.leftConsume||0)}"></div><div class="field"><label>저축</label><input class="input" type="number" data-act="leftSave" value="${A.esc(ACT.leftSave||0)}"></div><div class="field"><label>기부·나눔</label><input class="input" type="number" data-act="leftDonate" value="${A.esc(ACT.leftDonate||0)}"></div><div class="field"><label>예비비</label><input class="input" type="number" data-act="leftReserve" value="${A.esc(ACT.leftReserve||0)}"></div></div></div>`}
function step6(cfg){return `<div class="card"><h2>⑥ 샌드위치 전시 · 스티커 피드백</h2><div class="notice"><b>스티커는 우승 점수가 아닙니다.</b> 친구들의 소비자 반응을 관찰하는 자료입니다. 자기 조에는 붙이지 않습니다.</div><div class="grid3">${cfg.stickerCategories.map((c,i)=>`<div class="field"><label>${A.esc(c)}</label><input class="input" type="number" min="0" data-act="sticker${i}" value="${A.esc(ACT['sticker'+i]||0)}"><div class="muted">받은 스티커 수</div></div>`).join('')}</div></div>`}
function summary(cfg,t){const x=actual(t),sticks=cfg.stickerCategories.map((c,i)=>`${c} ${ACT['sticker'+i]||0}개`).join(' / ');return `🥪 ${TEAM}조 · ${ACT.productName||'우리 조 샌드위치'}\n\n[경매 결과]\n메인: ${x.main?.itemName||'-'}\n추가재료: ${x.addons.map(a=>a.itemName).join(', ')||'-'}\n총 낙찰 지출: ${A.money(x.spent)} / 남은 예산: ${A.money(A.remaining(t,cfg))}\n\n[상품]\n판매가격: ${ACT.salePrice?Number(ACT.salePrice).toLocaleString('ko-KR')+'원':'-'}\n대상: ${ACT.target||'-'}\n한 줄 소개: ${ACT.tagline||'-'}\n\n[경제적 선택]\n${ACT.bestChoice||'-'}\n경험한 개념: ${(ACT.concepts||[]).join(', ')||'-'}\n\n[스티커 반응]\n${sticks}\n\n📷 완성 샌드위치 사진과 활동지 사진은 Padlet에서 직접 첨부합니다.`}
function step7(cfg,t){return `<div class="card"><h2>⑦ Padlet에 우리 조 결과 공유</h2><div class="summary">${A.esc(summary(cfg,t))}</div><div class="controls"><button id="copySummary" class="btn">📋 Padlet용 짧은 글 복사</button><a class="btn warn" href="${A.esc(cfg.padletUrl||'#')}" target="_blank">🟪 Padlet 열기</a><button id="printAll" class="btn light">🖨 1~7단계 전체 기록 인쇄/PDF</button></div><div class="warnbox">사진 파일은 웹에서 자동으로 Padlet에 전송되지 않습니다. 완성 샌드위치 사진과 활동지 사진은 Padlet에서 직접 첨부해 주세요.</div></div>`}
function render(){if(!ROOM)return;const cfg=ROOM.config,t=ROOM.teams?.[TEAM],st=ROOM.state||{};if(!t)return;let html='';if(STEP===0)html=auctionPage(cfg,t,st);else if(STEP===1)html=planHtml(cfg);else if(STEP===2)html=step2(cfg,t);else if(STEP===3)html=step3(cfg);else if(STEP===4)html=step4(cfg);else if(STEP===5)html=step5(cfg,t);else if(STEP===6)html=step6(cfg);else html=step7(cfg,t);$('#content').innerHTML=html;bindInputs();bindDynamic(cfg,t,st)}
function bindDynamic(cfg,t,st){$$('.chooseMain').forEach(b=>b.onclick=()=>A.set(A.roomPath(ROOMCODE,'mainSelections',TEAM),b.dataset.id));$$('.offerChoice').forEach(b=>b.onclick=()=>A.set(A.roomPath(ROOMCODE,'participation',st.offer.id,TEAM),b.dataset.v==='true'));if(st.offer&&(st.offer.qualifiedTeams||[]).includes(TEAM)){A.read(A.roomPath(ROOMCODE,'participation',st.offer.id,TEAM)).then(v=>{const x=$('#myOffer');if(x)x.textContent=v===true?'✅ 참여 선택됨':v===false?'⏭ 패스 선택됨':'아직 선택하지 않았습니다.'})}const a=st.currentAuction;if(a?.stage==='bidding'&&(a.eligibleTeams||[]).includes(TEAM)){if(timerHandle)clearInterval(timerHandle);const bidPath=A.roomPath(ROOMCODE,'bids',a.id,TEAM);A.read(bidPath).then(v=>{if(v?.amount&&$('#bidAmount'))$('#bidAmount').value=v.amount;if($('#myBid')&&v?.amount)$('#myBid').textContent='제출 완료 · 우리 조 입찰가 '+A.money(v.amount)});$('#bidBtn')?.addEventListener('click',async()=>{const amt=+$('#bidAmount').value,rem=A.remaining(t,cfg);if(amt<a.minimumBid)return alert('최소 입찰가보다 낮습니다.');if(amt>rem)return alert('남은 예산을 넘을 수 없습니다.');await A.set(bidPath,{amount:amt,at:firebase.database.ServerValue.TIMESTAMP});$('#myBid').textContent='제출 완료 · 우리 조 입찰가 '+A.money(amt)});timerHandle=setInterval(()=>{const el=$('.timer');if(!el)return;const r=Math.max(0,Math.ceil((a.endsAt-Date.now())/1000));el.textContent=r+'초';if(r<=0)clearInterval(timerHandle)},500)}$('#copySummary')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(summary(cfg,t));alert('Padlet용 짧은 글을 복사했습니다.')});$('#printAll')?.addEventListener('click',()=>printReport(cfg,t))}
function printReport(cfg,t){const x=actual(t),w=window.open('','_blank'),html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${TEAM}조 전체 기록</title><style>body{font-family:Arial,'Malgun Gothic';padding:24px;color:#17324d}h1{color:#0f7f74}.s{border:1px solid #b9c9da;border-left:6px solid #0f8b7d;border-radius:10px;padding:12px;margin:10px 0}b{color:#0d5267}</style></head><body><h1>🥪 샌드위치 경매 CEO · ${TEAM}조 전체 기록</h1><p><b>가상예산</b> ${A.money(cfg.teamBudget)} · <b>지출</b> ${A.money(x.spent)} · <b>남은 예산</b> ${A.money(A.remaining(t,cfg))}</p><div class="s"><h2>① 경매 전 계획</h2><p>이름: ${A.esc(ACT.planName||'-')}</p><p>원한 메인: ${A.esc(cfg.mainItems.find(i=>i.id===ACT.planMain)?.name||'-')}</p><p>최대 입찰 한도: ${A.esc(ACT.planMaxBid||'-')}</p><p>이유: ${A.esc(ACT.planReason||'-')}</p></div><div class="s"><h2>② 경매 후 실제 결과</h2><p>메인: ${A.esc(x.main?.itemName||'-')}</p><p>추가재료: ${A.esc(x.addons.map(a=>a.itemName).join(', ')||'-')}</p><p>달라진 점: ${A.esc(ACT.changes||'-')}</p><p>포기한 선택: ${A.esc(ACT.forgone||'-')}</p></div><div class="s"><h2>③ 우리 조 상품</h2><p>최종 이름: ${A.esc(ACT.productName||'-')}</p><p>판매가격: ${A.esc(ACT.salePrice||'-')}</p><p>대상: ${A.esc(ACT.target||'-')}</p><p>소개: ${A.esc(ACT.tagline||'-')}</p></div><div class="s"><h2>④ 경제회의</h2><p>경제개념: ${A.esc((ACT.concepts||[]).join(', ')||'-')}</p><p>잘한 선택: ${A.esc(ACT.bestChoice||'-')}</p><p>어려운 선택: ${A.esc(ACT.hardChoice||'-')}</p><p>다시 한다면: ${A.esc(ACT.retry||'-')}</p></div><div class="s"><h2>⑤ 남은 예산</h2><p>추가소비 ${A.esc(ACT.leftConsume||0)} / 저축 ${A.esc(ACT.leftSave||0)} / 기부·나눔 ${A.esc(ACT.leftDonate||0)} / 예비비 ${A.esc(ACT.leftReserve||0)}</p></div><div class="s"><h2>⑥ 스티커</h2>${cfg.stickerCategories.map((c,i)=>`<p>${A.esc(c)}: ${A.esc(ACT['sticker'+i]||0)}개</p>`).join('')}</div><div class="s"><h2>⑦ Padlet 공유용 요약</h2><pre>${A.esc(summary(cfg,t))}</pre></div></body></html>`;w.document.write(html);w.document.close();setTimeout(()=>w.print(),500)}
$('#joinBtn').onclick=joinRoom;$('#teamSelect').onchange=e=>switchTeam(e.target.value);$('#resetActivity').onclick=async()=>{if(confirm('현재 조의 활동기록만 초기화할까요? 경매 낙찰기록은 지워지지 않습니다.')){await A.remove(A.roomPath(ROOMCODE,'activity',TEAM));goto(1)}};$$('.tab').forEach(b=>b.onclick=()=>goto(b.dataset.step));init();
